=== therealivo8/MedTrack-FHIR/MDCalc_Schema.json
{
    "$id": "https://example.com/equations.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "description": "Schema for equations and related components",
    "type": "object",
    "properties": {
      "SystemId": { "type": "string" },
      "Name": { "type": "string" },
      "description": { "type": "string" },
      "inputs": {
        "type": "array",
        "items": { "$ref": "#/$defs/input" }
      },
      "states": {
        "type": "array",
        "items": { "$ref": "#/$defs/state" }
      }
    },
    "required": ["SystemId", "Name", "description", "inputs", "states"],
    "$defs": {
      "input": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "value": { "type": "string" },
          "type": { "type": "string" },
          "enum_values": {
            "type": "array",
            "items": { "type": "string" }
          },
          "required": { "type": "boolean" },
          "unit": { "type": "string" }
        },
        "required": ["name", "value", "type", "required"]
      },
      "state": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "type": { "type": "string" },
          "transitions": {
            "type": "array",
            "items": { "$ref": "#/$defs/transition" }
          },
          "equation": { "type": "string" },
          "value": { "type": "string" },
          "unit": { "type": "string" },
          "description": { "type": "string" }
        },
        "required": ["name", "type"]
      },
      "transition": {
        "type": "object",
        "properties": {
          "conditions": { "type": "string" },
          "next_step": { "type": "string" }
        },
        "required": ["next_step"]
      }
    }
  }

=== therealivo8/MedTrack-FHIR/MDCalc_Equations/MDCalc_FIB4_Index_for_Liver_Fibrosis.json
{
    "SystemId": "MDCalc 49",
    "Name": "Fibrosis-4 (FIB-4) Index for Liver Fibrosis",
    "description": "Noninvasive estimate of liver scarring in HCV and HBV patients, to assess need for biopsy.",
    "inputs": [
        {
            "name": "age",
            "unit": "years",
            "value": "30",
            "type": "float",
            "required": true
        },
        {
            "name": "AST",
            "unit": "U/L",
            "value": "20",
            "type": "float",
            "required": true
        },
        {
            "name": "ALT",
            "unit": "U/L",
            "value": "20",
            "type": "float",
            "required": true
        },
        {
            "name": "platelet_count",
            "unit": "*10³/µL",
            "value": "200",
            "type": "float",
            "required": true
        }
    ],
    "states": [
        {
            "name": "calculate_fib4",
            "type": "calculation",
            "equation": "$FIB4$ = ($age$ * $AST$) / ($platelet_count$ * math.sqrt($ALT$))",
            "transitions": [
                {
                    "next_step" : "FIB4_output"
                }
            ]
        },
        {
            "name": "FIB4_score_output",
            "type" : "output",
            "unit": "FIB-4 score",
            "description": "Fibrosis-4 (FIB-4) Index for Liver Fibrosis. Interpretation of FIB-4 Score: <1.45 (0-1), 1.45-3.25 (2-3), >3.25 (4-6). Use with caution in patients <35 or >65 years old, as the score has been shown to be less reliable in these patients."
        }
    ]
}

=== therealivo8/MedTrack-FHIR/MDCalc_Equations/MDCalc_SAAG.json
{
    "SystemId": "MDCalc 2",
    "Name": "Serum Ascites Albumin Gradient (SAAG)",
    "description": "Defines the presence of portal hypertension in patients with ascites.",
    "inputs": [
        {
            "name": "albumin_serum",
            "unit": "g/dL",
            "value": "5.5",
            "type": "float",
            "required": true
        },
        {
            "name": "albumin_ascitic_fluid",
            "unit": "g/dL",
            "value": "4",
            "type": "float",
            "required": true
        }
    ],
    "states": [
        {
            "name": "calculate_saag",
            "type": "calculation",
            "equation": "$SAAG$ = $albumin_serum$ - $albumin_ascitic_fluid$",
            "transitions": [
                {
                    "next_step" : "SAAG_output"
                }
            ]
        },
        {
            "name": "SAAG_output",
            "type" : "output",
            "unit": "g/dL",
            "description": "Serum Ascites Albumin Gradient.",
            "meaning": [
                {
                    "condition": "$SAAG$ > 1.1",
                    "message": "SAAG > 1.1 g/dL indicates portal hypertension is likely the cause of ascites with 97% accuracy."
                },
                {
                    "condition": "$SAAG$ <= 1.1",
                    "message": "SAAG scores do not indicate the cause of the portal hypertension."
                }
            ]
        }
    ]
}

=== therealivo8/MedTrack-FHIR/MDCalc_Equations/MDCalc_Bicarbonate_Deficit.json
{
    "SystemId": "MDCalc 51",
    "Name": "Bicarbonate Deficit",
    "description": "Calculates the total body bicarbonate deficit.",
    "inputs": [
        {
            "name": "weight",
            "unit": "lbs",
            "value": "100",
            "type": "float",
            "required": true
        },
        {
            "name": "bicarbonate",
            "unit": "mEq/L",
            "value": "25",
            "type": "float",
            "required": true
        }
    ],
    "states": [
        {
            "name": "calculate_bicarbonate_deficit",
            "type": "calculation",
            "equation": "$bicarbonate_deficit$ = 0.4 * ($weight$ / 2.20462) * (24 - $bicarbonate$)",
            "transitions": [
                {
                    "next_step" : "bicarbonate_deficit_output"
                }
            ]
        },
        {
            "name": "bicarbonate_deficit",
            "type" : "output",
            "unit": "mEq",
            "description": "Total body bicarbonate deficit."
        }
    ]
}

=== therealivo8/MedTrack-FHIR/MDCalc_Equations/MDCalc_Calcium_Correction_for_Hypoalbuminemia_and_Hyperalbuminemia.json
{
    "SystemId": "MDCalc 48",
    "Name": "Calcium Correction for Hypoalbuminemia and Hyperalbuminemia",
    "description": "Calculates a corrected calcium level for patients with hypoalbuminemia or hyperalbuminemia.",
    "inputs": [
        {
            "name": "calcium",
            "unit": "mg/dL",
            "value": "9.5",
            "type": "float",
            "required": true
        },
        {
            "name": "albumin",
            "unit": "g/dL",
            "value": "3.0",
            "type": "float",
            "required": true
        }
    ],
    "states": [
        {
            "name": "calculate_corrected_calcium",
            "type": "calculation",
            "equation": "$corrected_calcium$ = (0.8 * (4 - $albumin$)) + $calcium$",
            "transitions": [
                {
                    "next_step" : "corrected_calcium_output"
                }
            ]
        },
        {
            "name": "corrected_calcium_output",
            "type" : "output",
            "unit": "mg/dL",
            "description": "Corrected calcium level accounting for albumin levels."
        }
    ]
}

=== therealivo8/MedTrack-FHIR/MDCalc_Equations/MDCalc_Creatinine Clearance.json
{
    "SystemId": "MDCalc 43",
    "Name": "Creatinine Clearance (Cockcroft-Gault Equation)",
    "description": "Can be used to estimate kidney function for CKD staging. Can be used to adjust or discontinue medications based on kidney function.",
    "inputs": [
        {
            "name": "sex",
            "value": "M",
            "type": "enum",
            "enum_values": ["M", "F"],
            "required": true
        },
        {
            "name": "age",
            "unit": "years",
            "value": "25",
            "type": "float",
            "required": true
        },
        {
            "name": "weight",
            "unit": "lb",
            "value": "200",
            "type": "float",
            "required": true
        },
        {
            "name": "creatinine",
            "unit": "mg/dL",
            "value": "1.0",
            "type": "float",
            "required": true
        },
        {
            "name": "height",
            "unit": "in",
            "value": "72",
            "type": "float",
            "required": false
        }
    ],
    "states": [
        {
            "name": "determine_sex",
            "type": "conditional transition",
            "transitions": [
                {
                    "conditions": "$sex$ == 'M' and $height$ is None",
                    "next_step": "calculate_CrCl_with_exact_weight_male"
                },
                {
                    "conditions": "$sex$ == 'F' and $height$ is None",
                    "next_step": "calculate_CrCl_with_exact_weight_female"
                },
                {
                    "condition": "$sex$ == 'F' and $height$ is not None",
                    "next_step": "F_calculate_IBW"
                },
                {
                    "condition": "$sex$ == 'M' and $height$ is not None",
                    "next_step": "M_calculate_IBW"
                }
            ]
        },
        {
            "name": "M_calculate_IBW",
            "type": "calculation",
            "equation": "$IBW$ = 50 + [2.3 * ($height$ - 60)]",
            "transitions" : [
                {
                    "next_step":"M_calculate_ABW"
                }
            ]
        },
        {
            "name": "F_calculate_IBW",
            "type": "calculation",
            "equation": "$IBW$ = 45.5 + [2.3 * ($height$ - 60)]",
            "transitions" : [
                {
                    "next_step":"F_calculate_ABW"
                }
            ]
        },
        {
            "name": "F_calculate_ABW",
            "type": "calculation",
            "equation": "$ABW$ = $IBW$ + 0.4 * (($weight$ / 2.20462) - $IBW$)",
            "transitions" : [
                {
                    "next_step":"calculate_CrCl_with_adjusted_weight_female"
                }
            ]
        },
        {
            "name": "M_calculate_ABW",
            "type": "calculation",
            "equation": "$ABW$ = $IBW$ + 0.4 * (($weight$ / 2.20462) - $IBW$)",
            "transitions" : [
                {
                    "next_step":"calculate_CrCl_with_adjusted_weight_male"
                }
            ]
        },
        {
            "name": "calculate_CrCl_with_exact_weight_male",
            "type": "calculation",
            "equation": "$CrCl$ = (140 - $age$) * ($weight$ / 2.20462) * (1.0) / (72 * $creatinine$)",
            "transitions" : [
                {
                    "next_step":"CrCl_output_no_height"
                }
            ]
        },
        {
            "name": "calculate_CrCl_with_exact_weight_female",
            "type": "calculation",
            "equation": "$CrCl$ = (140 - $age$) * ($weight$ / 2.20462) * (0.85) / (72 * $creatinine$)",
            "transitions" : [
                {
                    "next_step":"CrCl_output_no_height"
                }
            ]
        },
        {
            "name": "calculate_CrCl_with_adjusted_weight_male",
            "type": "calculation",
            "equation": "$CrCl$ = (140 - age) * ($ABW$) * (1.0) / (72 * $creatinine$)",
            "transitions" : [
                {
                    "next_step":"CrCl_output_height"
                }
            ]
        },
        {
            "name": "calculate_CrCl_with_adjusted_weight_female",
            "type": "calculation",
            "equation": "$CrCl$ = (140 - age) * ($ABW$) * (0.85) / (72 * $creatinine$)",
            "transitions" : [
                {
                    "next_step":"CrCl_output_height"
                }
            ]
        },
        {
            "name" : "CrCl_output_height",
            "type": "output",
            "unit" : "mL/min",
            "value" : "0.0",
            "description" : "original Cockcroft-Gault without height. Uses actual weight"
        },
        {
            "name" : "CrCl_output_no_height",
            "type": "output",
            "unit" : "mL/min",
            "value" : "0.0",
            "description" : "Cockcroft-Gault with height. Uses ABW"
        }
    ]
}

=== therealivo8/MedTrack-FHIR/MDCalc_Equations/MDCalc_LDL_Calculated.json
{
    "SystemId": "MDCalc 1",
    "Name": "LDL Cholesterol Calculation",
    "description": "Calculates LDL based on total cholesterol, HDL cholesterol, and triglycerides using the Friedewald formula.",
    "inputs": [
        {
            "name": "total_cholesterol",
            "unit": "mg/dL",
            "value": "180",
            "type": "float",
            "required": true
        },
        {
            "name": "hdl_cholesterol",
            "unit": "mg/dL",
            "value": "80",
            "type": "float",
            "required": true
        },
        {
            "name": "triglycerides",
            "unit": "mg/dL",
            "value": "100",
            "type": "float",
            "required": true
        }
    ],
    "states": [
        {
            "name": "calculate_ldl",
            "type": "calculation",
            "equation": "$LDL$ = $total_cholesterol$ - $hdl_cholesterol$ - ($triglycerides$ / 5.0)",
            "transitions": [
                {
                    "next_step" : "LDL_Calculated_output"
                }
            ]
        },
        {
            "name": "LDL_Calculated_output",
            "type" : "output",
            "unit": "mg/dL",
            "description": "Calculated LDL level using the Friedewald formula."
        }
    ]
}

=== therealivo8/MedTrack-FHIR/MDCalc_Equations/MDCalc_Fatty_Liver_Index.json
{
    "SystemId": "MDCalc 47",
    "Name": "Fatty Liver Index (FLI)",
    "description": "Diagnoses fatty liver using labs and exam findings.",
    "inputs": [
        {
            "name": "BMI",
            "unit": "kg/m²",
            "value": "24",
            "type": "float",
            "required": true
        },
        {
            "name": "waist_circumference",
            "unit": "in",
            "value": "32",
            "type": "float",
            "required": true
        },
        {
            "name": "GGT",
            "unit": "U/L",
            "value": "30",
            "type": "float",
            "required": true
        },
        {
            "name": "triglycerides",
            "unit": "mg/dL",
            "value": "120",
            "type": "float",
            "required": true
        }
    ],
    "states": [
        {
            "name": "calculate_y",
            "type": "calculation",
            "equation": "$y$ = 0.953 * ln($triglycerides$) + 0.139 * $BMI$ + 0.718 * ln($GGT$) + 0.053 * $waist_circumference$ * 2.54 - 15.745",
            "transitions": [
                {
                    "next_step" :"calculate_FLI"
                }
            ]
        },
        {
            "name": "calculate_FLI",
            "type": "calculation",
            "equation": "$FLI$ = math.exp($y$) / (1 + math.exp($y$)) * 100",
            "transitions": [
                {
                    "next_step" : "fatty_liver_index_output"
                }
            ]
        },
        {
            "name": "fatty_liver_index_output",
            "type" : "output",
            "unit": "",
            "description": "Fatty Liver Index (FLI). Your FLI is calculated. Fatty liver ruled out if FLI < 30 (LR- = 0.2). Indeterminate for FLI 30 to < 60. Fatty liver ruled in if FLI ≥ 60 (LR+ = 4.3)."
        }
    ]
}

=== therealivo8/MedTrack-FHIR/MDCalc_Equations/MDCALC_Fibrotic_NASH.json
{
    "SystemId": "MDCalc 44",
    "Name": "Fibrotic NASH Index (FNI)",
    "description": "Screens for fibrotic NASH in individuals at high risk for NAFLD.",
    "inputs": [
        {
            "name": "AST",
            "unit": "U/L",
            "value": "30",
            "type": "float",
            "required": true
        },
        {
            "name": "HbA1c",
            "unit": "% gly Hgb",
            "value": "5",
            "type": "float",
            "required": true
        },
        {
            "name": "HDL",
            "unit": "mg/dL",
            "value": "80",
            "type": "float",
            "required": true
        }
    ],
    "states": [
        {
            "name": "calculate_x",
            "type": "calculation",
            "equation": "$x$ = -10.33 + 2.54 * ln($AST$) + 3.86 * ln($HbA1c$) - 1.66 * ln($HDL$)",
            "transitions": []
        },
        {
            "name": "calculate_FNI",
            "type": "calculation",
            "equation": "$FNI$ = math.exp($x$) / (1 + math.exp($x$))",
            "transitions": [
                {
                    "next_step" : "predicted_probability_output"
                }
            ]
        },
        {
            "name" : "predicted_probability_output",
            "type" : "output",
            "unit": "%",
            "description": "Predicted probability of fibrotic NASH.Your predicted probability of fibrotic NASH is X%. Fibrotic NASH can be ruled out if the FNI value is â‰¤ 0.10."
        }
    ]
}
